server:
  port: 9001

spring:
  application:
    name: alibaba-nacos-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_springcloud?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B0
    username: root
    password: shehuan

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.sh.springcloud.bean



