server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true # 默认 true
    fetch-registry: true # 默认 true
    service-url:
      #      defaultZone: http://localhost:7001/eureka/ # 单机版
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/ # 集群版
