server:
  port: 8801
spring:
  application:
    name: stream-rabbitmq-provider
  rabbitmq: # RabbitMQ 配置
    host: localhost
    port: 5672
    username: admin
    password: 123456
  cloud:
    stream:
      bindings:
        stream-output:
          destination: stream-exchange # 交换机名称
#      rabbit:
#        bindings:
#          stream-output:
#            consumer:
#              exchangeType: fanout
eureka:
  client:
    register-with-eureka: true # 默认 true
    fetch-registry: true # 默认 true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/ # 集群版
  instance:
    prefer-ip-address: true # 在注册中心后台可以查看到服务的 ip 地址