server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: false # 默认 true，只作为消费者也可以不用注册到注册中心
    fetch-registry: true # 默认 true
    service-url:
      #      defaultZone: http://localhost:7001/eureka/ # 单机版
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/ # 集群版

feign:
  client:
    config:
      default: # 修改默认的超时时间，如果该时间小于被调用接口的响应时间，同时 OrderController 配置了错误降级处理（一般不建议这样做），则 OrderController 直接调用降级方法
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  compression: # 数据压缩
    request:
      enabled: true
      mime-types: text/html,application/json
      min-request-size: 2048
    response:
      enabled: true
  hystrix: # 开启 openfeign 的 hystrix 支持
    enabled: true

#logging:
#  level:
#    com.sh.springcloud.service.PaymentService: debug

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # openfeign 整合 hystrix 需要配置该超时时间，默认1000


