server:
  port: 81

spring:
  application:
    name: alibaba-nacos-order-service81
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719

feign:
  client:
    config:
      default: # 修改默认的超时时间
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  compression: # 数据压缩
    request:
      enabled: true
      mime-types: text/html,application/json
      min-request-size: 2048
    response:
      enabled: true
  sentinel:
    enabled: true # 打开feign对Sentinel的支持


management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  payment-service: http://alibaba-nacos-payment-service

resttemplate:
  sentinel:
    enabled: true